name: Sync Translations

permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write
  statuses: write

on:
  schedule:
    - cron: "0 */12 * * *" # Every 12 hours - https://crontab.guru/#0_*/12_*_*_*
  push:
    branches: [main]

jobs:
  crowdin:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          token: ${{ secrets.ACTIONS_PAT }}
      - name: Extract translations from templates
        run: |
          npm install
          echo "Running the translation script (extract-translations.js)"
          cd $(git rev-parse --show-toplevel)/scripts
          node extract-translations.js
          new_messages_json_hash="$(git hash-object $(git rev-parse --show-toplevel)/crowdin/messages.json)"
          echo "- [generated]: message.json hash is $new_messages_json_hash"
        shell: bash

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: true
          download_translations: true
          localization_branch_name: translations/l10n_crowdin
          create_pull_request: true
          pull_request_title: "translations: ðŸ“š sync translations with crowdin"
          pull_request_body: "translations: ðŸ“š sync translations with crowdin"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
